<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-PQ7IP8FG" failures="1" tests="1" name="cucumber.TestNGTestRunner" time="6.297" errors="0" timestamp="2024-11-02T14:48:28 IST" skipped="0">
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="6.297">
    <failure message="expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at saloni.stepDefinition.stepDefinitionimpl.message_is_displayed_on_confirmation_page(stepDefinitionimpl.java:62)
at âœ½."Thankyou for the order." message is displayed on confirmationPage(file:///C:/Users/saloni%20jain/eclipse-workspace/projectfarmework/src/test/java/cucumber/PurchaseOrder.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumber.TestNGTestRunner -->
